### ISSUE TITLE
first time install error.

### ISSUE THREAD

**Issue by grimdour** [rootCBR/DisruptManager#24]
![image](https://github.com/user-attachments/assets/eaff5513-ae66-4a14-8e16-d9c45a3e5f1b)

**Comment by JoshFanti** [comment]
Got the same one tonight

**Comment by byronvaz47** [comment]
this shit is annoying does anyone not know a fix or whats causing this?? i checked the dir its saying the file is in and i have a patch.fat but no patch1.fat wtf??

**Comment by rootCBR** [comment]
See https://github.com/rootCBR/DisruptManager/issues/23#issuecomment-2585329454.

Verify that you set everything up correctly. If that doesn't help, there might be a bug.

**Comment by rootCBR** [comment]
I've released an update that should fix the problem. 

https://github.com/rootCBR/DisruptManager/releases

Let me know if it works.

**Comment by ImmortalVRC** [comment]
This issue is still persisting for me.

**Comment by leo13578** [comment]
root can you plz fix this patch.1.fat issue.

**Comment by Pepper134** [comment]
the update didn't work for me at all. the patch1.fat file is still missing.

**Comment by froomfie** [comment]
does anyone have a fix or an alternative to disrupt

**Comment by SilentWorkForce** [comment]
Doesnt work, same issue.

**Comment by rootCBR** [comment]
Give the new update a try and see if it's fixed

**Comment by YeraTV** [comment]
Still not working : 
Not saving the path of WDL
No folder "data_win64" so no file "patch1.fat"

**Comment by Neon-Reaper** [comment]
Using latest ver. and this is still happening. 
Debug log for reference: 

[debug.log](https://github.com/user-attachments/files/21313340/debug.log)

**Comment by tarnishedXsoul** [comment]
https://github.com/rootCBR/DisruptManager/issues/10#issuecomment-3411504156

this should help
@grimdour @SilentWorkForce @rootCBR @JoshFanti @Pepper134 @YeraTV @Neon-Reaper @froomfie @leo13578 @byronvaz47

**Comment by A-Assuncao** [comment]
![Image](https://github.com/user-attachments/assets/dea42db4-8bc8-4516-b20d-f29317d0d035)

You’re trying to install mods for **Watch Dogs Legion**, but the **game directory was configured under the wrong profile** (e.g., the _Watch Dogs_ profile instead of the _Watch Dogs Legion_ profile).

Because of that, DisruptManager ends up using the **wrong file expectations** for the selected folder and throws:

`FileNotFoundException: ...\data_win64\patch1.fat`

This is misleading, because **Watch Dogs Legion** normally uses:

-   `patch.fat` / `patch.dat`    
-   plus language packs like `patch_brazilian.*`, `patch_english.*`, etc.
    
While `patch1.fat/dat` is typical of **Watch Dogs 2** (and may also appear in older/other profile logic). So the folder is usually fine — the issue is that the **folder is being handled by the wrong game profile**.

### Fix (user-side)

1.  Open **Profiles**.    
2.  Click/select **“Watch Dogs Legion”** (not Watch Dogs / Watch Dogs 2).    
3.  Set the **Game Directory** for Legion there.    
4.  Also make sure the **Watch Dogs Legion checkbox is enabled**, so it appears in the dropdown list while DisruptManager is open.    
5.  Retry the install.
    
### Suggestion (developer-side)

It would help a lot if the tool could **warn the user when the selected directory doesn’t match the active profile**, instead of failing later with a missing-file exception (which looks like a broken install). This would prevent a very common user mistake and reduce confusion/support requests.

**Comment by tarnishedXsoul** [comment]
i was installing them for watch dogs 2 not watch dogs legion but i did get them to work

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
